CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(5)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),
    login varchar(40),
    name varchar(40),
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id),
    CONSTRAINT pk_user_user_ids PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    description varchar,
    release_date date,
    genre_id integer REFERENCES genres(id),
    rating_id integer REFERENCES ratings(id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id integer REFERENCES films(id),
    user_id integer REFERENCES users(id),
    CONSTRAINT pk_film_user_ids PRIMARY KEY (film_id, user_id)
);